routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ExchangeController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductMapController;
use App\Http\Controllers\client;
use App\Http\Controllers\TalentController;
use App\Models\ProductCategory;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/client');

// Dashboard
Route::get('/kadin',[MemberController::class,'index']);

// Anggota
Route::resource('anggota-person',MemberController::class);

// Badan usaha
Route::resource('anggota-badan-usaha',CompanyController::class);

// Kategori Produk
Route::resource('kategori-produk',ProductCategoryController::class);

// Produk
Route::resource('produk',ProductController::class);

// Sebaran Produk
Route::resource('peta-komoditas',ProductMapController::class);

// Bursa Produk
Route::resource('bursa-komoditas',ExchangeController::class);

// Potensi Produk Seluruh Kecamatan
Route::get('promap', function(){
    return view('kadin.promap',['type_menu'=>'bursa','title'=>'Peta Komoditas']);
});

// Unggah Foto Produk
Route::post('setFotoProduk', [ProductController::class, 'updateImage']);
// Pencari kerja - admin
Route::resource('talents', TalentController::class);

// Pencari kerja - talent
Route::get('talent/register', function (request $request) {
    return view('talent.register',['request'=>$request]);
});
Route::get('talent', function () {
    return view('talent.index');
});

// Route Untuk Client Pemesan Potensi Produk
Route::controller(client::class)->group(function () {
    Route::get('client', 'index');
    Route::get('order', 'create');
});
// Contekan Stisla
Route::get('/cek', function(){
    return view('pages.forms-advanced-form',['type_menu'=>'dashboard']);
});

// Routes Stisla
// Dashboard
Route::get('/dashboard-general-dashboard', function () {
    return view('pages.dashboard-general-dashboard', ['type_menu' => 'dashboard']);
});
Route::get('/dashboard-ecommerce-dashboard', function () {
    return view('pages.dashboard-ecommerce-dashboard', ['type_menu' => 'dashboard']);
});


// Layout
Route::get('/layout-default-layout', function () {
    return view('pages.layout-default-layout', ['type_menu' => 'layout']);
});

// Blank Page
Route::get('/blank-page', function () {
    return view('pages.blank-page', ['type_menu' => '']);
});

// Bootstrap
Route::get('/bootstrap-alert', function () {
    return view('pages.bootstrap-alert', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-badge', function () {
    return view('pages.bootstrap-badge', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-breadcrumb', function () {
    return view('pages.bootstrap-breadcrumb', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-buttons', function () {
    return view('pages.bootstrap-buttons', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-card', function () {
    return view('pages.bootstrap-card', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-carousel', function () {
    return view('pages.bootstrap-carousel', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-collapse', function () {
    return view('pages.bootstrap-collapse', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-dropdown', function () {
    return view('pages.bootstrap-dropdown', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-form', function () {
    return view('pages.bootstrap-form', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-list-group', function () {
    return view('pages.bootstrap-list-group', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-media-object', function () {
    return view('pages.bootstrap-media-object', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-modal', function () {
    return view('pages.bootstrap-modal', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-nav', function () {
    return view('pages.bootstrap-nav', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-navbar', function () {
    return view('pages.bootstrap-navbar', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-pagination', function () {
    return view('pages.bootstrap-pagination', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-popover', function () {
    return view('pages.bootstrap-popover', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-progress', function () {
    return view('pages.bootstrap-progress', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-table', function () {
    return view('pages.bootstrap-table', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-tooltip', function () {
    return view('pages.bootstrap-tooltip', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-typography', function () {
    return view('pages.bootstrap-typography', ['type_menu' => 'bootstrap']);
});


// components
Route::get('/components-article', function () {
    return view('pages.components-article', ['type_menu' => 'components']);
});
Route::get('/components-avatar', function () {
    return view('pages.components-avatar', ['type_menu' => 'components']);
});
Route::get('/components-chat-box', function () {
    return view('pages.components-chat-box', ['type_menu' => 'components']);
});
Route::get('/components-empty-state', function () {
    return view('pages.components-empty-state', ['type_menu' => 'components']);
});
Route::get('/components-gallery', function () {
    return view('pages.components-gallery', ['type_menu' => 'components']);
});
Route::get('/components-hero', function () {
    return view('pages.components-hero', ['type_menu' => 'components']);
});
Route::get('/components-multiple-upload', function () {
    return view('pages.components-multiple-upload', ['type_menu' => 'components']);
});
Route::get('/components-pricing', function () {
    return view('pages.components-pricing', ['type_menu' => 'components']);
});
Route::get('/components-statistic', function () {
    return view('pages.components-statistic', ['type_menu' => 'components']);
});
Route::get('/components-tab', function () {
    return view('pages.components-tab', ['type_menu' => 'components']);
});
Route::get('/components-table', function () {
    return view('pages.components-table', ['type_menu' => 'components']);
});
Route::get('/components-user', function () {
    return view('pages.components-user', ['type_menu' => 'components']);
});
Route::get('/components-wizard', function () {
    return view('pages.components-wizard', ['type_menu' => 'components']);
});

// forms
Route::get('/forms-advanced-form', function () {
    return view('pages.forms-advanced-form', ['type_menu' => 'forms']);
});
Route::get('/forms-editor', function () {
    return view('pages.forms-editor', ['type_menu' => 'forms']);
});
Route::get('/forms-validation', function () {
    return view('pages.forms-validation', ['type_menu' => 'forms']);
});

// google maps
// belum tersedia

// modules
Route::get('/modules-calendar', function () {
    return view('pages.modules-calendar', ['type_menu' => 'modules']);
});
Route::get('/modules-chartjs', function () {
    return view('pages.modules-chartjs', ['type_menu' => 'modules']);
});
Route::get('/modules-datatables', function () {
    return view('pages.modules-datatables', ['type_menu' => 'modules']);
});
Route::get('/modules-flag', function () {
    return view('pages.modules-flag', ['type_menu' => 'modules']);
});
Route::get('/modules-font-awesome', function () {
    return view('pages.modules-font-awesome', ['type_menu' => 'modules']);
});
Route::get('/modules-ion-icons', function () {
    return view('pages.modules-ion-icons', ['type_menu' => 'modules']);
});
Route::get('/modules-owl-carousel', function () {
    return view('pages.modules-owl-carousel', ['type_menu' => 'modules']);
});
Route::get('/modules-sparkline', function () {
    return view('pages.modules-sparkline', ['type_menu' => 'modules']);
});
Route::get('/modules-sweet-alert', function () {
    return view('pages.modules-sweet-alert', ['type_menu' => 'modules']);
});
Route::get('/modules-toastr', function () {
    return view('pages.modules-toastr', ['type_menu' => 'modules']);
});
Route::get('/modules-vector-map', function () {
    return view('pages.modules-vector-map', ['type_menu' => 'modules']);
});
Route::get('/modules-weather-icon', function () {
    return view('pages.modules-weather-icon', ['type_menu' => 'modules']);
});

// auth
Route::get('/auth-forgot-password', function () {
    return view('pages.auth-forgot-password', ['type_menu' => 'auth']);
});
Route::get('/auth-login', function () {
    return view('pages.auth-login', ['type_menu' => 'auth']);
});
Route::get('/auth-login2', function () {
    return view('pages.auth-login2', ['type_menu' => 'auth']);
});
Route::get('/auth-register', function () {
    return view('pages.auth-register', ['type_menu' => 'auth']);
});
Route::get('/auth-reset-password', function () {
    return view('pages.auth-reset-password', ['type_menu' => 'auth']);
});

// error
Route::get('/error-403', function () {
    return view('pages.error-403', ['type_menu' => 'error']);
});
Route::get('/error-404', function () {
    return view('pages.error-404', ['type_menu' => 'error']);
});
Route::get('/error-500', function () {
    return view('pages.error-500', ['type_menu' => 'error']);
});
Route::get('/error-503', function () {
    return view('pages.error-503', ['type_menu' => 'error']);
});

// features

app/Models/talent.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class talent extends Model
{
    use HasFactory;
    protected $table = 'talent';
    protected $guarded = ['id'];
}

app/Http/Controllers/TalentController.php
<?php

namespace App\Http\Controllers;

use App\Models\talent;
use App\Models\skills;
use Illuminate\Http\Request;

class TalentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $naker = talent::latest()->paginate(20);
        return view('kadin.talent',[
            'type_menu'=>'Talent',
            'title'=>'Pencari Kerja'
        ])->with(['talents'=>$naker]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(request $request)
    {
        return view('kadin.talent-form')->with(['request'=>$request]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->insertSkills($request->keahlian);
        talent::create($request->all());
        if($request->redir == "talent/register"){
            return redirect()->to('/talent/register')->with(['success'=>'Pendaftaran berhasil']);
        }else{
            return redirect()->route('talents.index')->with(['success'=> 'Data talent tersimpan']);
        }
    }

    private function insertSkills($skills){
        $keahlian = explode(", ", $skills);
        foreach($keahlian as $skill){
            skills::insertOrIgnore(['skill'=>$skill]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\talent  $talent
     * @return \Illuminate\Http\Response
     */
    public function show(talent $talent)
    {
        return view('kadin.talent-info')->with(['type_menu'=>'Talent','title'=>'Pencari Kerja','talent' => $talent]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\talent  $talent
     * @return \Illuminate\Http\Response
     */
    public function edit(talent $talent)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\talent  $talent
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, talent $talent)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\talent  $talent
     * @return \Illuminate\Http\Response
     */
    public function destroy(talent $talent)
    {
        //
    }

    // API responses
    public function skills(){
        $skills = talent::get('keahlian');
        return view('talent.skills', ['skills' => $skills]);
    }
}

resources/views/talent/form.blade.php
<h3 class="py-5 text-center">Formulir Head Hunter</h3>
<form action="{{ route('talents.store') }}" method="post" class="py-3 mb-5">
@csrf
<input type="hidden" id="redir" name="redir" value="{{ $request->path() }}">
<div class="form-group row">
    <label for="nik" class="col-sm-3">Nomor KTP</label>
    <div class="col-sm-9">
        <input type="text" name="nik" id="nik" class="form-control" value="">
    </div>
</div>
<div class="form-group row">
    <label for="namaLengkap" class="col-sm-3">Nama Lengkap</label>
    <div class="col-sm-9">
        <input type="text" name="namaLengkap" id="namaLengkap" class="form-control" value="">
    </div>
</div>
<div class="form-group row">
    <label for="jnKelamin" class="col-sm-3">Jenis Kelamin</label>
    <div class="col-sm-9">
        <select name="jnKelamin" id="jnKelamin" class="form-control">
            <option value="Laki-laki">Laki-laki</option>
            <option value="Perempuan">Perempuan</option>
        </select>
    </div>
</div>
<div class="form-group row">
    <label for="templatLahir" class="col-sm-3">Tempat Lahir</label>
    <div class="col-sm-9">
        <input type="text" name="templatLahir" id="templatLahir" class="form-control" value="Banjarnegara">
    </div>
</div>
<div class="form-group row">
    <label for="tanggalLahir" class="col-sm-3">Tanggal Lahir</label>
    <div class="col-sm-9">
        <input type="date" name="tanggalLahir" id="tanggalLahir" class="form-control" value="1990-01-01">
    </div>
</div>
<div class="form-group row">
    <label for="alamat" class="col-sm-3">Alamat</label>
    <div class="col-sm-9">
        <input type="text" name="alamat" id="alamat" class="form-control" value="">
    </div>
</div>
<div class="form-group row">
    <label for="pendidikanTerakhir" class="col-sm-3">Pendidikan Terakhir</label>
    <div class="col-sm-9">
        <select name="pendidikanTerakhir" id="pendidikanTerakhir" class="form-control">
            <option value="SLTP">SMP / MTs Sederajat</option>
            <option value="SLTA">SMA / SMK / MA Sederajat</option>
            <option value="Diploma 3">Diploma 3</option>
            <option value="Sarjana">Sarjana S1</option>
        </select>
    </div>
</div>
<div class="form-group row">
    <label for="keahlian" class="col-sm-3">Keahlian</label>
    <div class="col-sm-9">
        <input type="text" name="keahlian" id="keahlian" class="form-control" value="">
        <small>Pisahkan dengan tanda koma</small>
    </div>
</div>
{{-- nik , namaLengkap , jnKelamin , tempatLahir , tanggalLahir , alamat , pendidikanTerakhir ,  keahlian , email , telepon , deskripsi --}}
<div class="form-group row">
    <label for="email" class="col-sm-3">Email aktif</label>
    <div class="col-sm-9">
        <input type="emai" name="email" id="email" class="form-control" value="">
    </div>
</div>
<div class="form-group row">
    <label for="telepon" class="col-sm-3">Nomor Telepon</label>
    <div class="col-sm-9">
        <input type="text" name="telepon" id="telepon" class="form-control" value="">
    </div>
</div>
<div class="form-group row">
    <label for="deskripsi" class="col-sm-3">Deskripsi</label>
    <div class="col-sm-9">
        <p><small>Deskripsikan diri Anda</small></p>
        <textarea name="deskripsi" id="deskripsi" class="form-control" style="resize:none;" rows="6"></textarea>
    </div>
</div>
<div class="text-center">
    <input type="submit" value="Daftar!" class="btn btn-primary btn-sm">
</div>
</form>

resources/views/talent/index.blade.php
@extends('layouts.client')

@section('main')
<header class="py-5">
    <div class="container px-lg-5">
        <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
            <div class="m-4 m-lg-5">
                <h1 class="display-5 fw-bold">Head Hunter</h1>
                <p class="fs-4">Halaman interaksi pengusaha dan pencari kerja di wilayah Kabupaten Banjarnegara</p>
                <a href="{{ url('/talent/register') }}" class="btn btn-sm btn-primary">Daftar!</a>
            </div>
        </div>
    </div>
</header>
<div class="row">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center" id="skills">

    </div>
</div>
@endsection
@section('modals')

@endsection
@section('skripsi')
<script>
    $('#keahlian').tokenfield({
        autocomplete:{
            source:['las listrik','las karbit','mekanik mobil','mekanik motor','jahit','tata rambut','tukang kayu','tukang batu','operator komputer','teknisi komputer','programmer komputer'],
            delay:100
        },
        showAutocompleteOnFocus: true
    });

    $(document).ready( function(){
        $.getJSON("{{ url('api/talentas') }}" , function(resp){
            $("#skills div").remove();
            $.each(resp.skills , function(i,data){
                $("#skills").append(`
                <div class="card mx-3 my-3">
                    <div class="card-body text-center">
                        <img src="https://static.vecteezy.com/system/resources/previews/016/325/062/original/head-hunter-male-icon-design-free-vector.jpg" style="width:120px;  ">
                    </div>
                    <div class="card-header text-center">
                        <strong>${data.skill}</strong>
                    </div>
                </div>
                `);
            })
        })
    })

</script>
@endsection

resources/views/talent/register.blade.php
@extends('layouts.client')

@section('main')
<div class="row">
    <div class="col-lg-6 mx-auto">
        @include('talent.form')
    </div>
</div>
@endsection
@section('modals')

@endsection
@section('skripsi')
<script>
    $('#keahlian').tokenfield({
        autocomplete:{
            source:['las listrik','las karbit','mekanik mobil','mekanik motor','jahit','tata rambut','tukang kayu','tukang batu','operator komputer','teknisi komputer','programmer komputer'],
            delay:100
        },
        showAutocompleteOnFocus: true
    });
</script>
@endsection

resources/views/talent/skills.blade.php
@foreach ( $skills as $skill )
    {{ $skill->keahlian }} <br/>
@endforeach
@php
    $keahlian =[];
    foreach($skills as $skill){
        $bidang = explode(',',$skill->keahlian);
        foreach($skill)
    }
@endphp