routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ExchangeController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductMapController;
use App\Http\Controllers\client;
use App\Http\Controllers\TalentController;
use App\Models\ProductCategory;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/client');

// Dashboard
Route::get('/kadin',[MemberController::class,'index']);

// Anggota
Route::resource('anggota-person',MemberController::class);

// Badan usaha
Route::resource('anggota-badan-usaha',CompanyController::class);

// Kategori Produk
Route::resource('kategori-produk',ProductCategoryController::class);

// Produk
Route::resource('produk',ProductController::class);

// Sebaran Produk
Route::resource('peta-komoditas',ProductMapController::class);

// Bursa Produk
Route::resource('bursa-komoditas',ExchangeController::class);

// Potensi Produk Seluruh Kecamatan
Route::get('promap', function(){
    return view('kadin.promap',['type_menu'=>'bursa','title'=>'Peta Komoditas']);
});

// Unggah Foto Produk
Route::post('setFotoProduk', [ProductController::class, 'updateImage']);
// Pencari kerja - admin
Route::resource('talents', TalentController::class);

// Pencari kerja - talent
Route::get('talent/register', function (request $request) {
    return view('talent.register',['request'=>$request]);
});
Route::get('talent', function () {
    return view('talent.index');
});

// Route Untuk Client Pemesan Potensi Produk
Route::controller(client::class)->group(function () {
    Route::get('client', 'index');
    Route::get('order', 'create');
});
// Contekan Stisla
Route::get('/cek', function(){
    return view('pages.forms-advanced-form',['type_menu'=>'dashboard']);
});

// Routes Stisla
// Dashboard
Route::get('/dashboard-general-dashboard', function () {
    return view('pages.dashboard-general-dashboard', ['type_menu' => 'dashboard']);
});
Route::get('/dashboard-ecommerce-dashboard', function () {
    return view('pages.dashboard-ecommerce-dashboard', ['type_menu' => 'dashboard']);
});


// Layout
Route::get('/layout-default-layout', function () {
    return view('pages.layout-default-layout', ['type_menu' => 'layout']);
});

// Blank Page
Route::get('/blank-page', function () {
    return view('pages.blank-page', ['type_menu' => '']);
});

// Bootstrap
Route::get('/bootstrap-alert', function () {
    return view('pages.bootstrap-alert', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-badge', function () {
    return view('pages.bootstrap-badge', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-breadcrumb', function () {
    return view('pages.bootstrap-breadcrumb', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-buttons', function () {
    return view('pages.bootstrap-buttons', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-card', function () {
    return view('pages.bootstrap-card', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-carousel', function () {
    return view('pages.bootstrap-carousel', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-collapse', function () {
    return view('pages.bootstrap-collapse', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-dropdown', function () {
    return view('pages.bootstrap-dropdown', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-form', function () {
    return view('pages.bootstrap-form', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-list-group', function () {
    return view('pages.bootstrap-list-group', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-media-object', function () {
    return view('pages.bootstrap-media-object', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-modal', function () {
    return view('pages.bootstrap-modal', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-nav', function () {
    return view('pages.bootstrap-nav', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-navbar', function () {
    return view('pages.bootstrap-navbar', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-pagination', function () {
    return view('pages.bootstrap-pagination', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-popover', function () {
    return view('pages.bootstrap-popover', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-progress', function () {
    return view('pages.bootstrap-progress', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-table', function () {
    return view('pages.bootstrap-table', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-tooltip', function () {
    return view('pages.bootstrap-tooltip', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-typography', function () {
    return view('pages.bootstrap-typography', ['type_menu' => 'bootstrap']);
});


// components
Route::get('/components-article', function () {
    return view('pages.components-article', ['type_menu' => 'components']);
});
Route::get('/components-avatar', function () {
    return view('pages.components-avatar', ['type_menu' => 'components']);
});
Route::get('/components-chat-box', function () {
    return view('pages.components-chat-box', ['type_menu' => 'components']);
});
Route::get('/components-empty-state', function () {
    return view('pages.components-empty-state', ['type_menu' => 'components']);
});
Route::get('/components-gallery', function () {
    return view('pages.components-gallery', ['type_menu' => 'components']);
});
Route::get('/components-hero', function () {
    return view('pages.components-hero', ['type_menu' => 'components']);
});
Route::get('/components-multiple-upload', function () {
    return view('pages.components-multiple-upload', ['type_menu' => 'components']);
});
Route::get('/components-pricing', function () {
    return view('pages.components-pricing', ['type_menu' => 'components']);
});
Route::get('/components-statistic', function () {
    return view('pages.components-statistic', ['type_menu' => 'components']);
});
Route::get('/components-tab', function () {
    return view('pages.components-tab', ['type_menu' => 'components']);
});
Route::get('/components-table', function () {
    return view('pages.components-table', ['type_menu' => 'components']);
});
Route::get('/components-user', function () {
    return view('pages.components-user', ['type_menu' => 'components']);
});
Route::get('/components-wizard', function () {
    return view('pages.components-wizard', ['type_menu' => 'components']);
});

// forms
Route::get('/forms-advanced-form', function () {
    return view('pages.forms-advanced-form', ['type_menu' => 'forms']);
});
Route::get('/forms-editor', function () {
    return view('pages.forms-editor', ['type_menu' => 'forms']);
});
Route::get('/forms-validation', function () {
    return view('pages.forms-validation', ['type_menu' => 'forms']);
});

// google maps
// belum tersedia

// modules
Route::get('/modules-calendar', function () {
    return view('pages.modules-calendar', ['type_menu' => 'modules']);
});
Route::get('/modules-chartjs', function () {
    return view('pages.modules-chartjs', ['type_menu' => 'modules']);
});
Route::get('/modules-datatables', function () {
    return view('pages.modules-datatables', ['type_menu' => 'modules']);
});
Route::get('/modules-flag', function () {
    return view('pages.modules-flag', ['type_menu' => 'modules']);
});
Route::get('/modules-font-awesome', function () {
    return view('pages.modules-font-awesome', ['type_menu' => 'modules']);
});
Route::get('/modules-ion-icons', function () {
    return view('pages.modules-ion-icons', ['type_menu' => 'modules']);
});
Route::get('/modules-owl-carousel', function () {
    return view('pages.modules-owl-carousel', ['type_menu' => 'modules']);
});
Route::get('/modules-sparkline', function () {
    return view('pages.modules-sparkline', ['type_menu' => 'modules']);
});
Route::get('/modules-sweet-alert', function () {
    return view('pages.modules-sweet-alert', ['type_menu' => 'modules']);
});
Route::get('/modules-toastr', function () {
    return view('pages.modules-toastr', ['type_menu' => 'modules']);
});
Route::get('/modules-vector-map', function () {
    return view('pages.modules-vector-map', ['type_menu' => 'modules']);
});
Route::get('/modules-weather-icon', function () {
    return view('pages.modules-weather-icon', ['type_menu' => 'modules']);
});

// auth
Route::get('/auth-forgot-password', function () {
    return view('pages.auth-forgot-password', ['type_menu' => 'auth']);
});
Route::get('/auth-login', function () {
    return view('pages.auth-login', ['type_menu' => 'auth']);
});
Route::get('/auth-login2', function () {
    return view('pages.auth-login2', ['type_menu' => 'auth']);
});
Route::get('/auth-register', function () {
    return view('pages.auth-register', ['type_menu' => 'auth']);
});
Route::get('/auth-reset-password', function () {
    return view('pages.auth-reset-password', ['type_menu' => 'auth']);
});

// error
Route::get('/error-403', function () {
    return view('pages.error-403', ['type_menu' => 'error']);
});
Route::get('/error-404', function () {
    return view('pages.error-404', ['type_menu' => 'error']);
});
Route::get('/error-500', function () {
    return view('pages.error-500', ['type_menu' => 'error']);
});
Route::get('/error-503', function () {
    return view('pages.error-503', ['type_menu' => 'error']);
});

// features

app/Http/Controllers/client.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Exchange;

class client extends Controller
{
    public function index(){
        return view('clients.index');
    }

    public function create(){
        return view('clients.inquiry-form',['type_menu'=>'bursa','title'=>'Sebaran Produk']);
    }
}

resources/views/clients/_template.blade.php
@extends('layouts.client')

@section('main')
<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center" id="apm">

</div>
@endsection
@section('modals')

@endsection
@section('skripsi')

@endsection

resources/views/clients/index.blade.php
@extends('layouts.client')

@section('main')
{{-- Jumbotron --}}
<!-- Header-->
<header class="py-5">
    <div class="container px-lg-5">
        <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
            <div class="m-4 m-lg-5">
                <h1 class="display-5 fw-bold">A warm welcome!</h1>
                <p class="fs-4">Bootstrap utility classes are used to create this jumbotron since the old component has been removed from the framework. Why create custom CSS when you can use utilities?</p>
            </div>
        </div>
    </div>
</header>
<!-- Page Content-->
<section class="pt-4">
    <div class="container px-lg-5">
{{-- Jumbotron --}}
        @if (session('success'))
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ session('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
          </div>
        @endif
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center" id="apm">

        </div>
    </div> {{-- end of container --}}
</section>
@endsection

@section('skripsi')
<script>
    $(document).ready( function(){
       $('#apm div').remove();
       $.getJSON("{{ url('api/allProductMap') }}",function(resp){
        $.each(resp.data , function(i , data){
            // skrip begin
            if(data.imgUrl== null){
                imgSrc = "https://dummyimage.com/450x300/dee2e6/6c757d.jpg";
            }else{
                imgSrc = "{{ asset('/storage') }}/"+data.imgUrl;
            }
            $('#apm').append(`
                <div class="card h-100 border-0">
                    <!-- Product image-->
                    <img class="card-img-top" src="${imgSrc}" style="margin-top:15px;">
                    <!-- Product details-->
                    <div class="card-body px-0 py-1">
                        <div class="text-center">
                            <!-- Product name-->
                            <p class="fw-bolder my-0" id="pn_${data.product_id}">${data.name}</p>
                            <!-- Product price-->
                            <p class="my-0">${parseInt(data.capacity).toLocaleString('id-ID')}</p>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent mt-2">
                        <div class="text-center">
                            <a class="btn btn-outline-dark btn-light-gray mt-auto setOrder" href="javascript:void(0)" id="mp_${data.product_id}">Buat Order</a>
                        </div>
                    </div>
                </div>
            `);
            // skrip ended
        })
       }); 
    });

    $('#apm').on('click','.setOrder',function(){
        let button_id = this.id.split('_');
        let pn_id = $('#pn_'+button_id[1]).text();
        localStorage.setItem('product_id',button_id[1]);
        localStorage.setItem('product_name',pn_id);
        window.location.href="{{ url('/order') }}";
    })
</script>
@endsection

resources/views/clients/inquiry-form.blade.php
@extends('layouts.client')

@section('main')
<div class="row">
    <div class="col-6 mx-auto py-5">

        <h3>Order Form</h3>
        <form action="{{ route('bursa-komoditas.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            {{-- ORDER ID --}}
            <div class="form-group kadin-row">
                <label for="id" class="col-sm-4">ORDER ID</label>
                <div class="col-sm-8">
                    <input type="text" name="id" id="id" class="form-control" readonly>
                </div>
            </div>
    
            {{-- Tanggal Order --}}
            <div class="form-group kadin-row">
                <label for="inquiryDate" class="col-sm-4">Tanggal Order</label>
                <div class="col-sm-8">
                    <input type="date" name="inquiryDate" id="inquiryDate" class="form-control" readonly value="{{ date('Y-m-d') }}">
                </div>
            </div>
           
            {{-- Nama Pemesan --}}            
            <div class="form-group kadin-row">
                <label for="applicantName" class="col-sm-4">Nama Pemesan</label>
                <div class="col-sm-8">
                    <input type="text" name="applicantName" id="applicantName" class="form-control">
                </div>
            </div>
            
            {{-- alamat pemesan --}}
            <div class="form-group kadin-row">
                <label for="applicantAddress" class="col-sm-4">Alamat Pemesan</label>
                <div class="col-sm-8">
                    <input type="text" name="applicantAddress" id="applicantAddress" class="form-control">
                </div>
            </div>

            {{-- email pemesan --}}
            <div class="form-group kadin-row">
                <label for="applicantEmail" class="col-sm-4">Alamat Email</label>
                <div class="col-sm-8">
                    <input type="email" name="applicantEmail" id="applicantEmail" class="form-control">
                </div>
            </div>
    
            {{-- Nomor Telepon Pemesan --}}
            <div class="form-group kadin-row">
                <label for="applicantPhone" class="col-sm-4">Nomor Telepon / Mobile</label>
                <div class="col-sm-8">
                    <input type="text" name="applicantPhone" id="applicantPhone" class="form-control">
                </div>
            </div>
            
            {{-- Kota Pemesan --}}
            <div class="form-group kadin-row">
                <label for="applicantCity" class="col-sm-4">Kota</label>
                <div class="col-sm-8">
                    <input type="text" name="applicantCity" id="applicantCity" class="form-control">
                </div>
            </div>
    
            {{-- Propinsi Pemesan  --}}
            <div class="form-group kadin-row">
                <label for="applicantProvince" class="col-sm-4">Propinsi</label>
                <div class="col-sm-8">
                    <input type="text" name="applicantProvince" id="applicantProvince" class="form-control">
                </div>
            </div>
    
            {{-- ID Produk --}}
            <div class="form-group kadin-row">
                <label for="product_name" class="col-sm-4">Nama Produk</label>
                <div class="col-sm-8">
                    <input type="hidden" name="product_id">
                    <input type="text" name="product_name" id="product_name" class="form-control">
                </div>
            </div>
            {{-- Jumlah Pesanan --}}
            <div class="form-group kadin-row">
                <label for="orderQuota" class="col-sm-4">Jumlah Dipesan</label>
                <div class="col-sm-8">
                    <input type="number" name="orderQuota" id="orderQuota" class="form-control">
                </div>
            </div>
            
            {{-- Batas Pemenuhan --}}
            <div class="form-group kadin-row">
                <label for="dueDate" class="col-sm-4">Batas Pemenuhan</label>
                <div class="col-sm-8">
                    <input type="date" name="dueDate" id="dueDate" class="form-control">
                </div>
            </div>
            <input type="hidden" name="route" value="client">
            <div class="form-group d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">Kirim Pesanan</button>
            </div>
        </form>
            {{--  --}}
            {{-- <div class="form-group row">
                <label for="xxx" class="col-sm-4"></label>
                <div class="col-sm-8">
                    <input type="text" name="xxx" id="xxx" class="form-control">
                </div>
            </div> --}}
    </div>
</div>
@endsection

@section('skripsi')
<script>
    $(document).ready(function(){
        const product_id = localStorage.getItem('product_id');
        const product_name = localStorage.getItem('product_name');
        $("input[name='product_id']").val(product_id);
        $("#product_name").val(product_name);
    })
</script>
@endsection