routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ExchangeController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductMapController;
use App\Http\Controllers\client;
use App\Http\Controllers\TalentController;
use App\Models\ProductCategory;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/client');

// Dashboard
Route::get('/kadin',[MemberController::class,'index']);

// Anggota
Route::resource('anggota-person',MemberController::class);

// Badan usaha
Route::resource('anggota-badan-usaha',CompanyController::class);

// Kategori Produk
Route::resource('kategori-produk',ProductCategoryController::class);

// Produk
Route::resource('produk',ProductController::class);

// Sebaran Produk
Route::resource('peta-komoditas',ProductMapController::class);

// Bursa Produk
Route::resource('bursa-komoditas',ExchangeController::class);

// Potensi Produk Seluruh Kecamatan
Route::get('promap', function(){
    return view('kadin.promap',['type_menu'=>'bursa','title'=>'Peta Komoditas']);
});

// Unggah Foto Produk
Route::post('setFotoProduk', [ProductController::class, 'updateImage']);
// Pencari kerja - admin
Route::resource('talents', TalentController::class);

// Pencari kerja - talent
Route::get('talent/register', function (request $request) {
    return view('talent.register',['request'=>$request]);
});
Route::get('talent', function () {
    return view('talent.index');
});

// Route Untuk Client Pemesan Potensi Produk
Route::controller(client::class)->group(function () {
    Route::get('client', 'index');
    Route::get('order', 'create');
});
// Contekan Stisla
Route::get('/cek', function(){
    return view('pages.forms-advanced-form',['type_menu'=>'dashboard']);
});

// Routes Stisla
// Dashboard
Route::get('/dashboard-general-dashboard', function () {
    return view('pages.dashboard-general-dashboard', ['type_menu' => 'dashboard']);
});
Route::get('/dashboard-ecommerce-dashboard', function () {
    return view('pages.dashboard-ecommerce-dashboard', ['type_menu' => 'dashboard']);
});


// Layout
Route::get('/layout-default-layout', function () {
    return view('pages.layout-default-layout', ['type_menu' => 'layout']);
});

// Blank Page
Route::get('/blank-page', function () {
    return view('pages.blank-page', ['type_menu' => '']);
});

// Bootstrap
Route::get('/bootstrap-alert', function () {
    return view('pages.bootstrap-alert', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-badge', function () {
    return view('pages.bootstrap-badge', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-breadcrumb', function () {
    return view('pages.bootstrap-breadcrumb', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-buttons', function () {
    return view('pages.bootstrap-buttons', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-card', function () {
    return view('pages.bootstrap-card', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-carousel', function () {
    return view('pages.bootstrap-carousel', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-collapse', function () {
    return view('pages.bootstrap-collapse', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-dropdown', function () {
    return view('pages.bootstrap-dropdown', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-form', function () {
    return view('pages.bootstrap-form', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-list-group', function () {
    return view('pages.bootstrap-list-group', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-media-object', function () {
    return view('pages.bootstrap-media-object', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-modal', function () {
    return view('pages.bootstrap-modal', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-nav', function () {
    return view('pages.bootstrap-nav', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-navbar', function () {
    return view('pages.bootstrap-navbar', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-pagination', function () {
    return view('pages.bootstrap-pagination', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-popover', function () {
    return view('pages.bootstrap-popover', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-progress', function () {
    return view('pages.bootstrap-progress', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-table', function () {
    return view('pages.bootstrap-table', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-tooltip', function () {
    return view('pages.bootstrap-tooltip', ['type_menu' => 'bootstrap']);
});
Route::get('/bootstrap-typography', function () {
    return view('pages.bootstrap-typography', ['type_menu' => 'bootstrap']);
});


// components
Route::get('/components-article', function () {
    return view('pages.components-article', ['type_menu' => 'components']);
});
Route::get('/components-avatar', function () {
    return view('pages.components-avatar', ['type_menu' => 'components']);
});
Route::get('/components-chat-box', function () {
    return view('pages.components-chat-box', ['type_menu' => 'components']);
});
Route::get('/components-empty-state', function () {
    return view('pages.components-empty-state', ['type_menu' => 'components']);
});
Route::get('/components-gallery', function () {
    return view('pages.components-gallery', ['type_menu' => 'components']);
});
Route::get('/components-hero', function () {
    return view('pages.components-hero', ['type_menu' => 'components']);
});
Route::get('/components-multiple-upload', function () {
    return view('pages.components-multiple-upload', ['type_menu' => 'components']);
});
Route::get('/components-pricing', function () {
    return view('pages.components-pricing', ['type_menu' => 'components']);
});
Route::get('/components-statistic', function () {
    return view('pages.components-statistic', ['type_menu' => 'components']);
});
Route::get('/components-tab', function () {
    return view('pages.components-tab', ['type_menu' => 'components']);
});
Route::get('/components-table', function () {
    return view('pages.components-table', ['type_menu' => 'components']);
});
Route::get('/components-user', function () {
    return view('pages.components-user', ['type_menu' => 'components']);
});
Route::get('/components-wizard', function () {
    return view('pages.components-wizard', ['type_menu' => 'components']);
});

// forms
Route::get('/forms-advanced-form', function () {
    return view('pages.forms-advanced-form', ['type_menu' => 'forms']);
});
Route::get('/forms-editor', function () {
    return view('pages.forms-editor', ['type_menu' => 'forms']);
});
Route::get('/forms-validation', function () {
    return view('pages.forms-validation', ['type_menu' => 'forms']);
});

// google maps
// belum tersedia

// modules
Route::get('/modules-calendar', function () {
    return view('pages.modules-calendar', ['type_menu' => 'modules']);
});
Route::get('/modules-chartjs', function () {
    return view('pages.modules-chartjs', ['type_menu' => 'modules']);
});
Route::get('/modules-datatables', function () {
    return view('pages.modules-datatables', ['type_menu' => 'modules']);
});
Route::get('/modules-flag', function () {
    return view('pages.modules-flag', ['type_menu' => 'modules']);
});
Route::get('/modules-font-awesome', function () {
    return view('pages.modules-font-awesome', ['type_menu' => 'modules']);
});
Route::get('/modules-ion-icons', function () {
    return view('pages.modules-ion-icons', ['type_menu' => 'modules']);
});
Route::get('/modules-owl-carousel', function () {
    return view('pages.modules-owl-carousel', ['type_menu' => 'modules']);
});
Route::get('/modules-sparkline', function () {
    return view('pages.modules-sparkline', ['type_menu' => 'modules']);
});
Route::get('/modules-sweet-alert', function () {
    return view('pages.modules-sweet-alert', ['type_menu' => 'modules']);
});
Route::get('/modules-toastr', function () {
    return view('pages.modules-toastr', ['type_menu' => 'modules']);
});
Route::get('/modules-vector-map', function () {
    return view('pages.modules-vector-map', ['type_menu' => 'modules']);
});
Route::get('/modules-weather-icon', function () {
    return view('pages.modules-weather-icon', ['type_menu' => 'modules']);
});

// auth
Route::get('/auth-forgot-password', function () {
    return view('pages.auth-forgot-password', ['type_menu' => 'auth']);
});
Route::get('/auth-login', function () {
    return view('pages.auth-login', ['type_menu' => 'auth']);
});
Route::get('/auth-login2', function () {
    return view('pages.auth-login2', ['type_menu' => 'auth']);
});
Route::get('/auth-register', function () {
    return view('pages.auth-register', ['type_menu' => 'auth']);
});
Route::get('/auth-reset-password', function () {
    return view('pages.auth-reset-password', ['type_menu' => 'auth']);
});

// error
Route::get('/error-403', function () {
    return view('pages.error-403', ['type_menu' => 'error']);
});
Route::get('/error-404', function () {
    return view('pages.error-404', ['type_menu' => 'error']);
});
Route::get('/error-500', function () {
    return view('pages.error-500', ['type_menu' => 'error']);
});
Route::get('/error-503', function () {
    return view('pages.error-503', ['type_menu' => 'error']);
});

// features

resources/views/kadin/anggota-form.blade.php
@php
    $ms = array();
    if($member == null){
        $ms=[
            'ig'=>'',
            'fb'=>'',
            'tw'=>'',
            'yt'=>'',
            'tt'=>''
    ];
        // $ms['ig']='';
        // $ms['fb']='';
        // $ms['tw']='';
        // $ms['yt']='';
        // $ms['tt']='';
    }else{
        $medsoc = json_decode($member->medsocs);
    }
@endphp
@extends('layouts.app-kadin')

@section('title', 'Form Kadin')

@push('style')
    <!-- CSS Libraries -->
    <link rel="stylesheet"
        href="{{ asset('library/bootstrap-daterangepicker/daterangepicker.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/selectric/public/selectric.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/bootstrap-timepicker/css/bootstrap-timepicker.min.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/bootstrap-tagsinput/dist/bootstrap-tagsinput.css') }}">
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header"><h1>{{ $title }}</h1></div>
            <div class="section-body">
                {{-- Sub Judul --}}
                <h2 class="section-title">Kamar Dagang dan Industri</h2>
                <p class="section-lead">Kabupaten Banjarnegara</p>
                {{-- Baris Formulir --}}
                <div class="row">
                    
                    <div class="col-md-6 mx-auto">
                        {{-- @dd($member); --}}
                        @if ($member == null )
                            <form action="{{ route('anggota-person.store') }}" method="post" enctype="multipart/form-data">
                        @else
                            <form action="{{ route('anggota-person.update',$member->id) }}" method="post" enctype="multipart/form-data">
                            @method('PUT')
                        @endif

                            @csrf
                            {{-- elemen --}}
                            <input type="hidden" name="id" value="{{ $member == null ? "" : $member->id }}">
                            {{-- elemen --}}
                            <div class="form-group">
                                <label>Nama Lengkap</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fa-regular fa-circle-user"></i>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control" name="fullName" id="fullName" placeholder="Nama Lengkap"
                                    value = "{{ $member == null ? "" : $member['fullName'] }}"
                                    >
                                </div>
                            </div>
                            {{-- elemen --}}
                            <div class="form-group">
                                <label>Alamat Rumah</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fa-solid fa-location-dot"></i>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control" name="address" id="address" placeholder="Alamat Rumah"
                                    value = "{{ $member == null ? "" : $member['address'] }}"
                                    >
                                </div>
                            </div>
                            {{-- elemen --}}
                            <div class="form-group">
                                <label>Alamat Email</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fa-solid fa-at"></i>
                                        </div>
                                    </div>
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Alamat Email"
                                    value = "{{ $member == null ? "" : $member['email'] }}"
                                    >
                                </div>
                            </div>
                            {{-- elemen --}}
                            <div class="form-group">
                                <label>Nomor Telepon</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fa-solid fa-mobile-screen"></i>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control purchase-code" name="phone" id="phone" placeholder="0812-3456-7890" 
                                    value = "{{ $member == null ? "" : $member['phone'] }}"
                                    >
                                </div>
                            </div>
                            
                            {{-- elemen --}}
                            <div class="form-group">
                                <label>Media Social</label>
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fa-brands fa-instagram"></i>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control socmed" id="Instagram" placeholder="Instagram"
                                    value="{{ $member == null ? "" : $medsoc->Instagram }}">
                                </div>
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fa-brands fa-facebook"></i>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control socmed" id="Facebook" placeholder="Facebook"
                                    value="{{ $member == null ? "" : $medsoc->Facebook }}">
                                </div>
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fa-brands fa-twitter"></i>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control socmed" id="Twitter" placeholder="Twitter"
                                    value="{{ $member == null ? "" : $medsoc->Twitter }}">
                                </div>
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fa-brands fa-youtube"></i>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control socmed" id="Youtube" placeholder="Youtube"
                                    value="{{ $member == null ? "" : $medsoc->Youtube }}">
                                </div>
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fa-brands fa-tiktok"></i>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control socmed" id="Tiktok" placeholder="Tiktok"
                                    value="{{ $member == null ? "" : $medsoc->Tiktok }}">
                                </div>
                            </div>
                            <input type="hidden" name="medsocs" id="socmed"
                            value="{{ $member == null ? "" : $member->medsocs }}"
                            >
                            <div class="form-group d-flex justify-content-end px-3">
                                <input type="reset" value="Ulangi" class="btn btn-warning mx-2">
                                <input type="submit" value="Simpan" class="btn btn-success mx-2">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->
    <script src="{{ asset('library/cleave.js/dist/cleave.min.js') }}"></script>
    <script src="{{ asset('library/cleave.js/dist/addons/cleave-phone.us.js') }}"></script>
    <script src="{{ asset('library/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="{{ asset('library/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js') }}"></script>
    <script src="{{ asset('library/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}"></script>
    <script src="{{ asset('library/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>
    <script src="{{ asset('library/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('library/selectric/public/jquery.selectric.min.js') }}"></script>

    <!-- Page Specific JS File -->
    {{-- <script src="{{ asset('js/page/forms-advanced-forms.js') }}"></script> --}}
    <script>
        // Cleave.Js Instantce
        var cleavePC = new Cleave(".purchase-code", {
            delimiter: "-",
            blocks: [4, 4, 4],
            uppercase: true,
        });
        // Cleave.Js Instantce
        const socmed = new Object();
        $(".socmed").change( function(){
            let media = this.id;
            let addrs = this.value;
            socmed[media] = addrs;
            $('#socmed').val( JSON.stringify(socmed) );
        })
    </script>
@endpush

resources/views/kadin/anggota.blade.php
@extends('layouts.app-kadin')

@section('title', $title)

@push('style')
    <!-- CSS Libraries -->
    <link rel="stylesheet"
        href="{{ asset('library/jqvmap/dist/jqvmap.min.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/summernote/dist/summernote-bs4.min.css') }}">
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>{{ $title }}</h1>
            </div>

            <div class="section-body">
                {{-- Sub Judul --}}
                <h2 class="section-title">Kamar Dagang dan Industri</h2>
                <p class="section-lead">Kabupaten Banjarnegara</p>

                {{-- Baris Tabel --}}
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{ $title }}</h4>
                            </div>
                            <div class="card-body">
                                <a href="{{ url('anggota-person/create') }}" class="badge badge-primary mb-3 p-3">
                                    <i class="fa-solid fa-plus"></i> Anggota
                                </a>
                                <div class="table-responsive">
                                    <table class="table table-bordered table-sm">
                                        <thead class='bg-success text-dark text-center'>
                                            <tr>
                                                {{-- <th>Nomor Induk Anggota</th> --}}
                                                <th>Nama Lengkap</th>
                                                <th>Alamat Tempat Tinggal</th>
                                                <th>Alamat Surat Elektronik</th>
                                                <th>Nomor Telephone</th>
                                                <th>Kendali</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($members as $member)
                                            @php
                                                $id = $member->id                                                
                                            @endphp
                                                <tr>
                                                    {{-- <td>{{ $member->id }}</td> --}}
                                                    <td>{{ $member->fullName }}</td>
                                                    <td>{{ $member->address }}</td>
                                                    <td>{{ $member->email }}</td>
                                                    <td>{{ $member->phone }}</td>
                                                    <td width="150px" class='text-center'>
                                                        <form action="{{ route('anggota-person.destroy',$id) }}" method="POST">
   
                                                            <a class="btn btn-sm mx-1 btn-primary" href="{{ route('anggota-person.show',$id) }}"><i class="fa-solid fa-user-tag"></i></a>
                                            
                                                            <a class="btn btn-sm mx-1 btn-warning" href="{{ route('anggota-person.edit',$id) }}"><i class="fa-solid fa-user-pen"></i></a>
                                           
                                                            @csrf
                                                            @method('DELETE')
                                              
                                                            <button type="submit" class="btn btn-sm mx-1 btn-danger"><i class="fa-solid fa-user-slash"></i></button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer text-right">
                                <p>Pagination Block</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->
    <script src="{{ asset('library/simpleweather/jquery.simpleWeather.min.js') }}"></script>
    <script src="{{ asset('library/chart.js/dist/Chart.min.js') }}"></script>
    <script src="{{ asset('library/jqvmap/dist/jquery.vmap.min.js') }}"></script>
    <script src="{{ asset('library/jqvmap/dist/maps/jquery.vmap.world.js') }}"></script>
    <script src="{{ asset('library/summernote/dist/summernote-bs4.min.js') }}"></script>
    <script src="{{ asset('library/chocolat/dist/js/jquery.chocolat.min.js') }}"></script>

    <!-- Page Specific JS File -->
    <script src="{{ asset('js/page/index-0.js') }}"></script>
@endpush

resources/views/kadin/badan-usaha.blade.php
@extends('layouts.app-kadin')

@section('title', 'Kadin Banjarnegara')

@push('style')
    <!-- CSS Libraries -->
    <link rel="stylesheet"
        href="{{ asset('library/jqvmap/dist/jqvmap.min.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/summernote/dist/summernote-bs4.min.css') }}">
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>{{ $title }}</h1>
            </div>

            <div class="section-body">
                {{-- Sub Judul --}}
                <h2 class="section-title">Kamar Dagang dan Industri</h2>
                <p class="section-lead">Kabupaten Banjarnegara</p>

                {{-- Baris Tabel --}}
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{ $title }}</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <a href="{{ url('anggota-badan-usaha/create') }}" class="badge badge-primary mb-3 p-3">
                                        <i class="fa-solid fa-plus"></i> Badan Usaha
                                    </a>
                                    <table class="table table-bordered table-sm">
                                        <thead class='bg-success text-dark text-center'>
                                            <tr>
                                                <th>Nama Perusahaan</th>
                                                <th>Alamat Domisili</th>
                                                <th>Jenis Usaha</th>
                                                <th>Nomor Telephone</th>
                                                <th>Alamat Surat Elektronik</th>
                                                <th>Kendali</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($companies as $company)
                                                <tr>
                                                    <td>{{ $company->name }}</td>
                                                    <td>{{ $company->address }}</td>
                                                    <td>{{ $company->businessCategory }}</td>
                                                    <td>{{ $company->phone }}</td>
                                                    <td>{{ $company->email }}</td>
                                                    <td width="150">
                                                        <form action="{{ route('anggota-badan-usaha.destroy',$company->id) }}" method="POST">
   
                                                            <a class="btn btn-sm mx-1 btn-primary" href="{{ route('anggota-badan-usaha.show',$company->id) }}"><i class="fa-solid fa-building"></i></a>
                                            
                                                            <a class="btn btn-sm mx-1 btn-warning" href="{{ route('anggota-badan-usaha.edit',$company->id) }}"><i class="fa-solid fa-pen-nib"></i></a>
                                           
                                                            @csrf
                                                            @method('DELETE')
                                              
                                                            <button type="submit" class="btn btn-sm mx-1 btn-danger"><i class="fa-solid fa-hammer"></i></button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer text-right">
                                <p>Pagination Block</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->
    <script src="{{ asset('library/simpleweather/jquery.simpleWeather.min.js') }}"></script>
    <script src="{{ asset('library/chart.js/dist/Chart.min.js') }}"></script>
    <script src="{{ asset('library/jqvmap/dist/jquery.vmap.min.js') }}"></script>
    <script src="{{ asset('library/jqvmap/dist/maps/jquery.vmap.world.js') }}"></script>
    <script src="{{ asset('library/summernote/dist/summernote-bs4.min.js') }}"></script>
    <script src="{{ asset('library/chocolat/dist/js/jquery.chocolat.min.js') }}"></script>

    <!-- Page Specific JS File -->
    <script src="{{ asset('js/page/index-0.js') }}"></script>
@endpush